# Generated by Django 4.2.11 on 2024-05-11 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
                ('parking_type', models.CharField(default='Bollard', max_length=255)),
                ('landmark', models.CharField(default='Marymount MRT', max_length=255)),
                ('latitude', models.FloatField(default=1.34972210693726)),
                ('longitude', models.FloatField(default=103.8390303269501)),
                ('city_name', models.CharField(default='Singapore', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
